The purpose of this file is to allow us to go step by step on how all functions work.
We also want to provide the opportunitiy to identify any issues within each function. 
Also, we would like to test how long each function takes to run.

The main function that we will be working with is known as the "process_it" function. 

This function does the following things: 

1. If there are any county values that we want to filter for, it will clean these up. 

By this, we mean that it standardize how each county is presented in the column. 
One thing to note is that in Louisiana counties are actually known as parishes. 
this is important because there are a lot of emitters in Louisiana. 

2. Next, the function inserts a location column 

3. Next, we filter the data by referring back to [1] if its length is positive. 

4. Next, we iterate through the filtered dataframe and inser any missing info. 

Mainly, we are grabbing unit type, parent company and fuel type. 

5. Next, we save the excel. 

6. Lastly, if user wants we then create a map that plots each facility 

We need to consider created a heatmap as well as it can be helpful.

First, let's load some packages that we will be using.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import functions as fs
import requests
from xml.etree import ElementTree as ET
import xml
from uszipcode import SearchEngine
import folium

AttributeError: module 'sqlalchemy_mate' has no attribute 'ExtendedBase'

Next, let's load our data as a pandas dataframe.

In [8]:
# we will be loading 2022 emissions data
df = pd.read_excel('ghgp_data_files/ghgp_data_2022.xlsx',
                    sheet_name='Direct Emitters', skiprows=3)

# let's see what our data looks like
print(df.describe())
print(df.info())

        Facility Id        FRS Id      Zip Code     Latitude    Longitude  \
count  6.491000e+03  6.325000e+03   6491.000000  6491.000000  6491.000000
mean   1.005753e+06  1.100347e+11  54205.365121    37.259143   -92.450338
std    4.026099e+03  2.896094e+07  26985.992487     5.990902    16.973396
min    1.000001e+06  1.100003e+11      0.000000    13.297100  -174.113611
25%    1.002432e+06  1.100024e+11  32533.000000    32.797318   -97.857184
50%    1.005123e+06  1.100332e+11  55337.000000    37.757930   -90.263967
75%    1.007824e+06  1.100701e+11  77507.000000    41.233660   -82.651856
max    1.014729e+06  1.100714e+11  99801.000000    71.292071   144.891130

       Primary NAICS Code  Total reported direct emissions  \
count         6367.000000                     6.491000e+03
mean        367896.649285                     3.857296e+05
std         144283.115806                     1.119423e+06
min         111419.000000                     0.000000e+00
25%         221112.000000                     3.320953e+04
50%         325199.000000                     6.687737e+04
75%         486210.000000                     1.879261e+05
max         928110.000000                     2.177544e+07

       CO2 emissions (non-biogenic)   Methane (CH4) emissions   \
count                   5.841000e+03              6.383000e+03
mean                    4.012173e+05              2.013747e+04
std                     1.164798e+06              8.041914e+04
min                     0.000000e+00              2.500000e-01
25%                     2.543350e+04              3.237500e+01
50%                     5.745920e+04              6.245000e+02
75%                     1.918502e+05              9.264854e+03
max                     2.160473e+07              2.527353e+06

       Nitrous Oxide (N2O) emissions   ...  Pulp and Paper Manufacturing  \
count                    5.447000e+03  ...                     100.00000
mean                     3.497111e+03  ...                   57884.45184
std                      5.227409e+04  ...                   32168.75734
min                      1.182182e-01  ...                       0.00000
25%                      1.788000e+01  ...                   36294.84100
50%                      4.023000e+01  ...                   56293.00200
75%                      2.111330e+02  ...                   77394.98600
max                      2.439796e+06  ...                  164388.41000

       Silicon Carbide Production  Soda Ash Manufacturing  \
count                         1.0                4.000000
mean                     102060.9           329607.400000
std                           NaN            25035.968366
min                      102060.9           293111.100000
25%                      102060.9           324695.400000
50%                      102060.9           337897.050000
75%                      102060.9           342809.050000
max                      102060.9           349524.400000

       Titanium Dioxide Production  Underground Coal Mines  Zinc Production  \
count                     6.000000            6.100000e+01         5.000000
mean                 208782.066667            4.329035e+05    110441.840000
std                  116034.315543            5.577900e+05     49373.001785
min                  100903.900000            0.000000e+00     61687.000000
25%                  126362.375000            5.422500e+04     75630.100000
50%                  186472.350000            1.656480e+05    102953.200000
75%                  238849.225000            6.543886e+05    124662.300000
max                  416209.900000            2.558194e+06    187276.600000

       Municipal Landfills  Industrial Wastewater Treatment  \
count         1.123000e+03                       114.000000
mean          7.224033e+04                     18244.256579
std           7.899706e+04                     34119.350030
min           1.735000e+02                         0.000000
25%           2.602000e+04                       795.312500
50%           5.102475e+04                      3529.875000
75%           9.303175e+04                     24469.250000
max           1.085939e+06                    256229.750000

       Manufacture of Electric Transmission and Distribution Equipment  \
count                                           5.000000
mean                                        26041.818458
std                                         21732.531969
min                                          1596.068400
25%                                          8573.438400
50%                                         29610.248290
75%                                         34293.525600
max                                         56135.811600

       Industrial Waste Landfills
count                  163.000000
mean                 42067.886139
std                  47351.895038
min                    153.750000
25%                   8107.875000
50%                  25912.500000
75%                  53919.625000
max                 229070.974255

[8 rows x 56 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6491 entries, 0 to 6490
Data columns (total 66 columns):
 #   Column                                                                                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                                                                                     --------------  -----
 0   Facility Id                                                                                                                                                                                6491 non-null   int64
 1   FRS Id                                                                                                                                                                                     6325 non-null   float64
 2   Facility Name                                                                                                                                                                              6491 non-null   object
 3   City                                                                                                                                                                                       6491 non-null   object
 4   State                                                                                                                                                                                      6491 non-null   object
 5   Zip Code                                                                                                                                                                                   6491 non-null   int64
 6   Address                                                                                                                                                                                    6036 non-null   object
 7   County                                                                                                                                                                                     6211 non-null   object
 8   Latitude                                                                                                                                                                                   6491 non-null   float64
 9   Longitude                                                                                                                                                                                  6491 non-null   float64
 10  Primary NAICS Code                                                                                                                                                                         6367 non-null   float64
 11  Industry Type (subparts)                                                                                                                                                                   6491 non-null   object
 12  Industry Type (sectors)                                                                                                                                                                    6491 non-null   object
 13  Total reported direct emissions                                                                                                                                                            6491 non-null   float64
 14  CO2 emissions (non-biogenic)                                                                                                                                                               5841 non-null   float64
 15  Methane (CH4) emissions                                                                                                                                                                    6383 non-null   float64
 16  Nitrous Oxide (N2O) emissions                                                                                                                                                              5447 non-null   float64
 17  HFC emissions                                                                                                                                                                              62 non-null     float64
 18  PFC emissions                                                                                                                                                                              59 non-null     float64
 19  SF6 emissions                                                                                                                                                                              59 non-null     float64
 20  NF3 emissions                                                                                                                                                                              46 non-null     float64
 21  Other Fully Fluorinated GHG emissions                                                                                                                                                      48 non-null     float64
 22  HFE emissions                                                                                                                                                                              24 non-null     float64
 23  Very Short-lived Compounds emissions                                                                                                                                                       27 non-null     float64
 24  Other GHGs (metric tons CO2e)                                                                                                                                                              9 non-null      float64
 25  Biogenic CO2 emissions (metric tons)                                                                                                                                                       543 non-null    float64
 26  Stationary Combustion                                                                                                                                                                      5438 non-null   float64
 27  Electricity Generation                                                                                                                                                                     1098 non-null   float64
 28  Adipic Acid Production                                                                                                                                                                     2 non-null      float64
 29  Aluminum Production                                                                                                                                                                        7 non-null      float64
 30  Ammonia Manufacturing                                                                                                                                                                      29 non-null     float64
 31  Cement Production                                                                                                                                                                          91 non-null     float64
 32  Electronics Manufacture                                                                                                                                                                    47 non-null     float64
 33  Ferroalloy Production                                                                                                                                                                      9 non-null      float64
 34  Fluorinated GHG Production                                                                                                                                                                 15 non-null     float64
 35  Glass Production                                                                                                                                                                           101 non-null    float64
 36  HCFC–22 Production from HFC–23 Destruction                                                                                                                                                 5 non-null      float64
 37  Hydrogen Production                                                                                                                                                                        113 non-null    float64
 38  Iron and Steel Production                                                                                                                                                                  121 non-null    float64
 39  Lead Production                                                                                                                                                                            11 non-null     float64
 40  Lime Production                                                                                                                                                                            68 non-null     float64
 41  Magnesium Production                                                                                                                                                                       9 non-null      float64
 42  Miscellaneous Use of Carbonates                                                                                                                                                            6 non-null      float64
 43  Nitric Acid Production                                                                                                                                                                     31 non-null     float64
 44  Petroleum and Natural Gas Systems – Offshore Production                                                                                                                                    116 non-null    float64
 45  Petroleum and Natural Gas Systems – Processing                                                                                                                                             429 non-null    float64
 46  Petroleum and Natural Gas Systems – Transmission/Compression                                                                                                                               642 non-null    float64
 47  Petroleum and Natural Gas Systems – Underground Storage                                                                                                                                    35 non-null     float64
 48  Petroleum and Natural Gas Systems – LNG Storage                                                                                                                                            5 non-null      float64
 49  Petroleum and Natural Gas Systems – LNG Import/Export                                                                                                                                      11 non-null     float64
 50  Petrochemical Production                                                                                                                                                                   76 non-null     float64
 51  Petroleum Refining                                                                                                                                                                         135 non-null    float64
 52  Phosphoric Acid Production                                                                                                                                                                 9 non-null      float64
 53  Pulp and Paper Manufacturing                                                                                                                                                               100 non-null    float64
 54  Silicon Carbide Production                                                                                                                                                                 1 non-null      float64
 55  Soda Ash Manufacturing                                                                                                                                                                     4 non-null      float64
 56  Titanium Dioxide Production                                                                                                                                                                6 non-null      float64
 57  Underground Coal Mines                                                                                                                                                                     61 non-null     float64
 58  Zinc Production                                                                                                                                                                            5 non-null      float64
 59  Municipal Landfills                                                                                                                                                                        1123 non-null   float64
 60  Industrial Wastewater Treatment                                                                                                                                                            114 non-null    float64
 61  Manufacture of Electric Transmission and Distribution Equipment                                                                                                                            5 non-null      float64
 62  Industrial Waste Landfills                                                                                                                                                                 163 non-null    float64
 63  Is some CO2 collected on-site and used to manufacture other products and therefore not emitted from the affected manufacturing process unit(s)? (as reported under Subpart G or S)         6491 non-null   object
 64  Is some CO2 reported as emissions from the affected manufacturing process unit(s) under Subpart AA, G or P collected and transferred off-site or injected (as reported under Subpart PP)?  6491 non-null   object
 65  Does the facility employ continuous emissions monitoring?                                                                                                                                  6491 non-null   object
dtypes: float64(54), int64(2), object(10)
memory usage: 3.3+ MB
None

Okay, now let's remove columns that we really don't need given they don't have
enough data or don't provide much insight.

In [9]:
# now we want to also only select the columns that we are interested in
keep_cols = ['Facility Id', 'Facility Name', 'City', 'State', 'Zip Code', 'Address', 
                'County', 'Latitude', 'Longitude', 'Primary NAICS Code', 'Industry Type (subparts)', 'Industry Type (sectors)', 
                'Total reported direct emissions', 'CO2 emissions (non-biogenic) ', 'Methane (CH4) emissions ', 'Stationary Combustion', 
                'Electricity Generation']

# now let's filter our data
df = df[keep_cols]

# now we want to rename the following columns to names that we can easily refer # to
new_cols = ['facility_id', 'facility_name', 'city', 'state', 'zipcode', 'address', 
            'county', 'latitude', 'longitude', 'primary_naics_code', 'idustry_type_subparts', 'industry_type_sectors', 'total_reported_e', 'co2_e', 'methane_e', 'stationary_comb_e', 'electricty_gen_e',]

# now we want to rename our columns to make more sense and be more accessible
df.columns = new_cols  

print(df.describe())
print(df.info())

        facility_id       zipcode     latitude    longitude  \
count  6.491000e+03   6491.000000  6491.000000  6491.000000
mean   1.005753e+06  54205.365121    37.259143   -92.450338
std    4.026099e+03  26985.992487     5.990902    16.973396
min    1.000001e+06      0.000000    13.297100  -174.113611
25%    1.002432e+06  32533.000000    32.797318   -97.857184
50%    1.005123e+06  55337.000000    37.757930   -90.263967
75%    1.007824e+06  77507.000000    41.233660   -82.651856
max    1.014729e+06  99801.000000    71.292071   144.891130

       primary_naics_code  total_reported_e         co2_e     methane_e  \
count         6367.000000      6.491000e+03  5.841000e+03  6.383000e+03
mean        367896.649285      3.857296e+05  4.012173e+05  2.013747e+04
std         144283.115806      1.119423e+06  1.164798e+06  8.041914e+04
min         111419.000000      0.000000e+00  0.000000e+00  2.500000e-01
25%         221112.000000      3.320953e+04  2.543350e+04  3.237500e+01
50%         325199.000000      6.687737e+04  5.745920e+04  6.245000e+02
75%         486210.000000      1.879261e+05  1.918502e+05  9.264854e+03
max         928110.000000      2.177544e+07  2.160473e+07  2.527353e+06

       stationary_comb_e  electricty_gen_e
count       5.438000e+03      1.098000e+03
mean        1.027232e+05      1.391753e+06
std         3.616650e+05      2.200726e+06
min         0.000000e+00      0.000000e+00
25%         4.900082e+03      9.734612e+04
50%         3.225827e+04      5.346794e+05
75%         7.234303e+04      1.706290e+06
max         1.064499e+07      2.177540e+07
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6491 entries, 0 to 6490
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   facility_id            6491 non-null   int64
 1   facility_name          6491 non-null   object
 2   city                   6491 non-null   object
 3   state                  6491 non-null   object
 4   zipcode                6491 non-null   int64
 5   address                6036 non-null   object
 6   county                 6211 non-null   object
 7   latitude               6491 non-null   float64
 8   longitude              6491 non-null   float64
 9   primary_naics_code     6367 non-null   float64
 10  idustry_type_subparts  6491 non-null   object
 11  industry_type_sectors  6491 non-null   object
 12  total_reported_e       6491 non-null   float64
 13  co2_e                  5841 non-null   float64
 14  methane_e              6383 non-null   float64
 15  stationary_comb_e      5438 non-null   float64
 16  electricty_gen_e       1098 non-null   float64
dtypes: float64(8), int64(2), object(7)
memory usage: 862.2+ KB
None

Okay, now let's clean our county values.

In [10]:
def clean_county_val(dataframe):
    '''
    The purpose of this function is to iterate through each row in our dfs and remove the word County from the County column value
    '''

    # these are the words that we want to remove
    words_to_remove = ['County', 'county', 'COUNTY', 'Parish', 'parish', 
                       'PARISH']

    # regular expression pattern to match any of the words 
    pattern = "|".join(words_to_remove)

    # removing the words from the column value 
    dataframe['county'] = dataframe['county'].str.replace(pattern, '', regex=True)

    # making all County names uppercase
    dataframe['county'] = dataframe['county'].str.upper()

    return dataframe

In [11]:
df = clean_county_val(dataframe=df)

print(df.describe())
print(df.info())

        facility_id       zipcode     latitude    longitude  \
count  6.491000e+03   6491.000000  6491.000000  6491.000000
mean   1.005753e+06  54205.365121    37.259143   -92.450338
std    4.026099e+03  26985.992487     5.990902    16.973396
min    1.000001e+06      0.000000    13.297100  -174.113611
25%    1.002432e+06  32533.000000    32.797318   -97.857184
50%    1.005123e+06  55337.000000    37.757930   -90.263967
75%    1.007824e+06  77507.000000    41.233660   -82.651856
max    1.014729e+06  99801.000000    71.292071   144.891130

       primary_naics_code  total_reported_e         co2_e     methane_e  \
count         6367.000000      6.491000e+03  5.841000e+03  6.383000e+03
mean        367896.649285      3.857296e+05  4.012173e+05  2.013747e+04
std         144283.115806      1.119423e+06  1.164798e+06  8.041914e+04
min         111419.000000      0.000000e+00  0.000000e+00  2.500000e-01
25%         221112.000000      3.320953e+04  2.543350e+04  3.237500e+01
50%         325199.000000      6.687737e+04  5.745920e+04  6.245000e+02
75%         486210.000000      1.879261e+05  1.918502e+05  9.264854e+03
max         928110.000000      2.177544e+07  2.160473e+07  2.527353e+06

       stationary_comb_e  electricty_gen_e
count       5.438000e+03      1.098000e+03
mean        1.027232e+05      1.391753e+06
std         3.616650e+05      2.200726e+06
min         0.000000e+00      0.000000e+00
25%         4.900082e+03      9.734612e+04
50%         3.225827e+04      5.346794e+05
75%         7.234303e+04      1.706290e+06
max         1.064499e+07      2.177540e+07
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6491 entries, 0 to 6490
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   facility_id            6491 non-null   int64
 1   facility_name          6491 non-null   object
 2   city                   6491 non-null   object
 3   state                  6491 non-null   object
 4   zipcode                6491 non-null   int64
 5   address                6036 non-null   object
 6   county                 6211 non-null   object
 7   latitude               6491 non-null   float64
 8   longitude              6491 non-null   float64
 9   primary_naics_code     6367 non-null   float64
 10  idustry_type_subparts  6491 non-null   object
 11  industry_type_sectors  6491 non-null   object
 12  total_reported_e       6491 non-null   float64
 13  co2_e                  5841 non-null   float64
 14  methane_e              6383 non-null   float64
 15  stationary_comb_e      5438 non-null   float64
 16  electricty_gen_e       1098 non-null   float64
dtypes: float64(8), int64(2), object(7)
memory usage: 862.2+ KB
None

Now, let's insert locations dependent on zipcode.

In [14]:
def zip_to_county(zipcode):

    '''
    The purpose of this file is to return a coutny when given a zipcode value. 

    Specifically, we will be working with an EPA Emissions data file for 2021 that provides us with emissions data for the united states. 

    The main issue is that the data is incomplete in terms of county values. 
    Thus, we need to go into each worksheet and fill in the county values by using the reported zipcodes that are included...
    '''

    search = SearchEngine()
    result = search.by_zipcode(zipcode)
    
    if result:
        return result.county
        
    else:
        return None


def insert_location(dataframe):

    '''
    The purpose of this function is to iterate through each row of a dataframe and add a county value if there is not one already there
    '''

    for index, row in dataframe.iterrows():

        # check if County column is empty 
        county_value = row['county']

        if pd.isna(county_value) or county_value == '':

            # 
            dataframe.at[index, 'county'] = zip_to_county(row['zipcode'])

        else:

            # if not empty, then just leave alone
            continue

    # now let's add a new column to our dataframe that adds the County and the State
    dataframe['location'] = dataframe['county'] + ', ' + dataframe['state']

    return dataframe

In [15]:
df = insert_location(dataframe=df)

print(df.describe())
print(df.info())

        facility_id       zipcode     latitude    longitude  \
count  6.491000e+03   6491.000000  6491.000000  6491.000000
mean   1.005753e+06  54205.365121    37.259143   -92.450338
std    4.026099e+03  26985.992487     5.990902    16.973396
min    1.000001e+06      0.000000    13.297100  -174.113611
25%    1.002432e+06  32533.000000    32.797318   -97.857184
50%    1.005123e+06  55337.000000    37.757930   -90.263967
75%    1.007824e+06  77507.000000    41.233660   -82.651856
max    1.014729e+06  99801.000000    71.292071   144.891130

       primary_naics_code  total_reported_e         co2_e     methane_e  \
count         6367.000000      6.491000e+03  5.841000e+03  6.383000e+03
mean        367896.649285      3.857296e+05  4.012173e+05  2.013747e+04
std         144283.115806      1.119423e+06  1.164798e+06  8.041914e+04
min         111419.000000      0.000000e+00  0.000000e+00  2.500000e-01
25%         221112.000000      3.320953e+04  2.543350e+04  3.237500e+01
50%         325199.000000      6.687737e+04  5.745920e+04  6.245000e+02
75%         486210.000000      1.879261e+05  1.918502e+05  9.264854e+03
max         928110.000000      2.177544e+07  2.160473e+07  2.527353e+06

       stationary_comb_e  electricty_gen_e
count       5.438000e+03      1.098000e+03
mean        1.027232e+05      1.391753e+06
std         3.616650e+05      2.200726e+06
min         0.000000e+00      0.000000e+00
25%         4.900082e+03      9.734612e+04
50%         3.225827e+04      5.346794e+05
75%         7.234303e+04      1.706290e+06
max         1.064499e+07      2.177540e+07
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6491 entries, 0 to 6490
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   facility_id            6491 non-null   int64
 1   facility_name          6491 non-null   object
 2   city                   6491 non-null   object
 3   state                  6491 non-null   object
 4   zipcode                6491 non-null   int64
 5   address                6036 non-null   object
 6   county                 6396 non-null   object
 7   latitude               6491 non-null   float64
 8   longitude              6491 non-null   float64
 9   primary_naics_code     6367 non-null   float64
 10  idustry_type_subparts  6491 non-null   object
 11  industry_type_sectors  6491 non-null   object
 12  total_reported_e       6491 non-null   float64
 13  co2_e                  5841 non-null   float64
 14  methane_e              6383 non-null   float64
 15  stationary_comb_e      5438 non-null   float64
 16  electricty_gen_e       1098 non-null   float64
 17  location               6396 non-null   object
dtypes: float64(8), int64(2), object(8)
memory usage: 912.9+ KB
None

Now, we want to go add 3 new cols of data that need to be grabbed from another
EPA related website. 
The key thing we need here is the ghgp id or the facility id.

First, let's load into our environment the meander_xml code that achieves this

In [16]:
def meander_xml(ghgp_id, topic, year=2022):

    '''
    Given a ghgp_id, return the fuel type within the xml code.
    The purpose of this function is extract and process an XML file.

    Not entirely sure what an XML file is, or how it compares to a JSON file but it seems
    very low memory and has a tree structure.

    This is how facilities provide reports to the EPA emissions entity. 

    Please note that you need to:

    'pip install elementpath' and then import the module into your env

    to import: 
    'xml.etree.ElementTree as ET'
    '''

    try:

        # here, we will be adding the ghgp_id value to a url used to make GET request
        url = f'https://ghgdata.epa.gov/ghgp/service/xml/{year}?id={ghgp_id}&et=undefined'

        # making the url GET request for the xml file
        response = requests.get(url=url)
        webpage_content = response.text

        # modifying our url contnet because it containts code we do not need
        lines = webpage_content[38:-6].split('\n')
        modified_content = '\n'.join(lines[1:])

        # parse the XML
        root = ET.fromstring(modified_content)

        # now we want to create an ifelse statement that will grab specific data
        # user needs

        if topic == 'Fuel Type' or topic == 'fuel type':

            # creating a list to return the found elements to
            fuel_types = []

            # extract the fuel type element
            for fuel_type in root.findall(".//FuelType"):

                # return the fuel_type value
                fuel_types.append(fuel_type.text)
            
            # removing redundancies
            fuel_types = list(set(fuel_types))

            # concatenating our list to output a long string
            fuel_typez = ", ".join([str(item) for item in fuel_types])

            return fuel_typez
    

        elif topic == 'Unit Type' or topic == 'unit type':
    
            # creating a list to return the found elements to
            unit_types = []

            # extract the unit type value
            for unit_type in root.findall('.//UnitType'):

                # return the unit_type value
                unit_types.append(unit_type.text)
            
            # removing redundancies
            unit_types = list(set(unit_types))

            # concatenating our list to output a long string
            unit_typez = ", ".join([str(item) for item in unit_types])

            return unit_typez
    

        elif topic =='Parent Company' or topic == 'parent company': 
        
            # creating a list to return the found elements to
            parent_cos = []
            
            # else, extract parent company name 
            for parent_co in root.findall('.//ParentCompanyLegalName'):

                # return the parent company name
                parent_cos.append(parent_co.text)
            
            # removing redundancies
            parent_cos = list(set(parent_cos))

            # concatenating our list to output a long string
            parent_coz = ", ".join([str(item) for item in parent_cos])

            return parent_coz
    

        else: 

            # means none of the 3 topics were given 
            print('Error: please insert a valid topic to receive a valid value!')


    except xml.etree.ElementTree.ParseError:
        # xml file is not properly formatted, so skip this iteration
        "sorry, bud!"
        pass

We have now loaded the code and now need to run it through every row in our df

In [ ]:
    # adding the needed empty columns in our dataframe
    # these columns will be populated with data from meander_xml function
    df['Unit Type'] = ''
    df['Parent Company'] = ''
    df['Fuel Type'] = ''   


    for index, row in df.iterrows():

        '''
        purpose is to go through, grab the 3 values and add them to the dataframe
        '''

        # defining our ghgp_id from the row we just grabbed
        ghgp = row['facility_id']
        print(ghgp)

        # now we will be grabbing and adding the 3 values to our datframe
        # adding a unit type value
        df.loc[index, 'Unit Type'] = meander_xml(ghgp_id=ghgp, topic='unit type')

        # adding a parent company value
        df.loc[index, 'Parent Company'] = meander_xml(ghgp_id=ghgp, topic='parent company')

        # adding a fuel type value
        df.loc[index, 'Fuel Type'] = meander_xml(ghgp_id=ghgp, topic='fuel type')